config/routes.rb
Jobportal::Application.routes.draw do
  
get "search/view"
get "home/index"
resources :resumes
resources :jobs do
    collection do
        get :search
    end
 end
 resources :jobseekers
 resources :admins
 resources :employs
 devise_for :users
 root :to => "home#index"
  

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_title %><br />
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :qulification %><br />
    <%= f.text_field :qulification %>
  </div>
  <div class="field">
    <%= f.label :experince %><br />
    <%= f.text_field :experince %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :no_of_post %><br />
    <%= f.text_field :no_of_post %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.number_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <tr>
    <th>Job title</th>
    <th>Company name</th>
    <th>Qulification</th>
    <th>Experince</th>
    <th>Summary</th>
    <th>No of post</th>
    <th>Contact number</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= admin.job_title %></td>
    <td><%= admin.company_name %></td>
    <td><%= admin.qulification %></td>
    <td><%= admin.experince %></td>
    <td><%= admin.summary %></td>
    <td><%= admin.no_of_post %></td>
    <td><%= admin.contact_number %></td>
    <td><%= admin.email %></td>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'post job', new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Job title:</b>
  <%= @admin.job_title %>
</p>

<p>
  <b>Company name:</b>
  <%= @admin.company_name %>
</p>

<p>
  <b>Qulification:</b>
  <%= @admin.qulification %>
</p>

<p>
  <b>Experince:</b>
  <%= @admin.experince %>
</p>

<p>
  <b>Summary:</b>
  <%= @admin.summary %>
</p>

<p>
  <b>No of post:</b>
  <%= @admin.no_of_post %>
</p>

<p>
  <b>Contact number:</b>
  <%= @admin.contact_number %>
</p>

<p>
  <b>Email:</b>
  <%= @admin.email %>
</p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>