config/routes.rb
Jobportal::Application.routes.draw do
  
get "search/view"
get "home/index"
resources :resumes
resources :jobs do
    collection do
        get :search
    end
 end
 resources :jobseekers
 resources :admins
 resources :employs
 devise_for :users
 root :to => "home#index"
  

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :company_name, :contact_number, :email, :experince, :job_title, :no_of_post, :qulification, :summary
    belongs_to :user 
    # searchable do
    #  text  :company_name, :job_title ,:qulification
    # end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = current_user.jobs    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end 

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end
  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
  
    @job = current_user.jobs.new(params[:job])
      
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
  # def search
  #     @job = Job.search do
  #       fulltext params[:query]
  #     end.results
  #       #@resultTransfer = @jobs.results
  #       #debugger
  #       #respond_to do |format|
  #       #format.html { redirect_to home_index_url(@resultTransfer) }
  #      # format.xml  { render :xml => @jobs }
       
  #       respond_to do |format|
  #       format.html { render  "home/index" }
  #       format.xml  { render :xml => @jobs }
       
        
  #   end
  #     #redirect_to search_view_path(params[:@resultTransfer])
  #  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @@job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_title %><br />
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :qulification %><br />
    <%= f.text_field :qulification %>
  </div>
  <div class="field">
    <%= f.label :experince %><br />
    <%= f.text_field :experince %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :no_of_post %><br />
    <%= f.text_field :no_of_post %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.number_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
</br>
</br>
</br>
<style type="text/css">
.img1{
        height: 100px;
        width: 50px;
      }
</style>
<div>
  <table>
     <tr>
       <th> Welcome</th>
       <th ><%=current_user.fist_name %><th>
     </tr>
  </table> 
  </br>
  </br>
  </br>
</div>
<div>
  <div style="float:left; width:800px; " >
    <table >
      <tr>
        <th>Job title</th>
        <th>Company name</th>
        <th>Qulification</th>
        <th>Experince</th>
        <th>Summary</th>
        <th>No of post</th>
        <th>Contact number</th>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.job_title %></td>
          <td><%= job.company_name %></td>
          <td><%= job.qulification %></td>
          <td><%= job.experince %></td>
          <td><%= job.summary %></td>
          <td><%= job.no_of_post %></td>
          <td><%= job.contact_number %></td>
          <td><%= job.email %></td>
          <td><%= link_to 'Show', job %></td>
          <td><%= link_to 'Edit', edit_job_path(job) %></td>
          <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
</table>
</div>
<div style="float:right ;width:350px; border-left-style:solid; margen-lefy:2px;">
  <table><th>your profile</th>
    <tr>
      <td>Your Email ID</td>
      <td><%= current_user.email %></td>
    </tr>
    <tr>
    <td>Name:</td><td><%= current_user.fist_name %><%= current_user.last_name %></td>
    </tr><tr>

    <td>contact number :</td><td><%= current_user.contact_number %></td>
  </tr>
  <tr>
    <td>Addrass:<%= current_user.addrass %></td>
 </tr>
  <tr>
    <td>Image</td>
     <td><%= image_tag "Mahatma.jpg", :class=>"img1" %>
</td>
  </tr>
</table>
</div></div>
 <%= link_to 'new job post ', new_job_path %>

 <%#= form_tag search_jobs_path, :method => :get do %>
  <%#= text_field_tag :query, params[:query] %> <%#= submit_tag "Search!" %>
<%# end %>
    

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>