config/routes.rb
Jobportal::Application.routes.draw do
  
get "search/view"
get "home/index"
resources :resumes
resources :jobs do
    collection do
        get :search
    end
 end
 resources :jobseekers
 resources :admins
 resources :employs
 devise_for :users
 root :to => "home#index"
  

end

app/models/jobseeker.rb
class Jobseeker < ActiveRecord::Base
  attr_accessible :DOB, :address, :contact_number, :father_name, :full_name, :gender, :mother_name, :pin_number, :primary_skills, :secondary_skills, :work_exp
end

app/controllers/jobseekers_controller.rb
class JobseekersController < ApplicationController
  # GET /jobseekers
  # GET /jobseekers.json
  def index
    @jobseekers = Jobseeker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobseekers }
    end
  end

  # GET /jobseekers/1
  # GET /jobseekers/1.json
  def show
    @jobseeker = Jobseeker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @jobseeker }
    end
  end

  # GET /jobseekers/new
  # GET /jobseekers/new.json
  def new
    @jobseeker = Jobseeker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jobseeker }
    end
  end

  # GET /jobseekers/1/edit
  def edit
    @jobseeker = Jobseeker.find(params[:id])
  end

  # POST /jobseekers
  # POST /jobseekers.json
  def create
    @jobseeker = Jobseeker.new(params[:jobseeker])

    respond_to do |format|
      if @jobseeker.save
        format.html { redirect_to @jobseeker, notice: 'Jobseeker was successfully created.' }
        format.json { render json: @jobseeker, status: :created, location: @jobseeker }
      else
        format.html { render action: "new" }
        format.json { render json: @jobseeker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobseekers/1
  # PUT /jobseekers/1.json
  def update
    @jobseeker = Jobseeker.find(params[:id])

    respond_to do |format|
      if @jobseeker.update_attributes(params[:jobseeker])
        format.html { redirect_to @jobseeker, notice: 'Jobseeker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @jobseeker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobseekers/1
  # DELETE /jobseekers/1.json
  def destroy
    @jobseeker = Jobseeker.find(params[:id])
    @jobseeker.destroy

    respond_to do |format|
      format.html { redirect_to jobseekers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/jobseekers_helper.rb
module JobseekersHelper
end

app/views/jobseekers/_form.html.erb
<%= form_for(@jobseeker) do |f| %>
  <% if @jobseeker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jobseeker.errors.count, "error") %> prohibited this jobseeker from being saved:</h2>

      <ul>
      <% @jobseeker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :father_name %><br />
    <%= f.text_field :father_name %>
  </div>
  <div class="field">
    <%= f.label :mother_name %><br />
    <%= f.text_field :mother_name %>
  </div>
  <div class="field">
    <%= f.label :DOB %><br />
    <%= f.text_field :DOB %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.number_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :pin_number %><br />
    <%= f.text_field :pin_number %>
  </div>
  <div class="field">
    <%= f.label :primary_skills %><br />
    <%= f.text_field :primary_skills %>
  </div>
  <div class="field">
    <%= f.label :secondary_skills %><br />
    <%= f.text_field :secondary_skills %>
  </div>
  <div class="field">
    <%= f.label :work_exp %><br />
    <%= f.number_field :work_exp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobseekers/edit.html.erb
<h1>Editing jobseeker</h1>

<%= render 'form' %>

<%= link_to 'Show', @jobseeker %> |
<%= link_to 'Back', jobseekers_path %>

app/views/jobseekers/index.html.erb
<h1>Listing jobseekers</h1>

<table>
  <tr>
    <th>Full name</th>
    <th>Father name</th>
    <th>Mother name</th>
    <th>Dob</th>
    <th>Gender</th>
    <th>Contact number</th>
    <th>Address</th>
    <th>Pin number</th>
    <th>Primary skills</th>
    <th>Secondary skills</th>
    <th>Work exp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobseekers.each do |jobseeker| %>
  <tr>
    <td><%= jobseeker.full_name %></td>
    <td><%= jobseeker.father_name %></td>
    <td><%= jobseeker.mother_name %></td>
    <td><%= jobseeker.DOB %></td>
    <td><%= jobseeker.gender %></td>
    <td><%= jobseeker.contact_number %></td>
    <td><%= jobseeker.address %></td>
    <td><%= jobseeker.pin_number %></td>
    <td><%= jobseeker.primary_skills %></td>
    <td><%= jobseeker.secondary_skills %></td>
    <td><%= jobseeker.work_exp %></td>
    <td><%= link_to 'Show', jobseeker %></td>
    <td><%= link_to 'Edit', edit_jobseeker_path(jobseeker) %></td>
    <td><%= link_to 'Destroy', jobseeker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'Creat profile', new_jobseeker_path %>
<%= link_to 'Creat resume', new_resume_path %>

app/views/jobseekers/new.html.erb
<h1>New jobseeker</h1>

<%= render 'form' %>

<%= link_to 'Back', jobseekers_path %>

app/views/jobseekers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Full name:</b>
  <%= @jobseeker.full_name %>
</p>

<p>
  <b>Father name:</b>
  <%= @jobseeker.father_name %>
</p>

<p>
  <b>Mother name:</b>
  <%= @jobseeker.mother_name %>
</p>

<p>
  <b>Dob:</b>
  <%= @jobseeker.DOB %>
</p>

<p>
  <b>Gender:</b>
  <%= @jobseeker.gender %>
</p>

<p>
  <b>Contact number:</b>
  <%= @jobseeker.contact_number %>
</p>

<p>
  <b>Address:</b>
  <%= @jobseeker.address %>
</p>

<p>
  <b>Pin number:</b>
  <%= @jobseeker.pin_number %>
</p>

<p>
  <b>Primary skills:</b>
  <%= @jobseeker.primary_skills %>
</p>

<p>
  <b>Secondary skills:</b>
  <%= @jobseeker.secondary_skills %>
</p>

<p>
  <b>Work exp:</b>
  <%= @jobseeker.work_exp %>
</p>


<%= link_to 'Edit', edit_jobseeker_path(@jobseeker) %> |
<%= link_to 'Back', jobseekers_path %>